# Generated by Django 5.1.1 on 2024-10-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('entrenador', 'Entrenador'), ('nutricionista', 'Nutricionista')], default='cliente', max_length=20),
        ),
    ]
