# Generated by Django 5.1.1 on 2024-10-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Imagen',
        ),
    ]
