# Generated by Django 5.1.1 on 2024-10-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
    ]
