# Generated by Django 5.1.1 on 2024-10-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_musclegroup_alter_exercise_media_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutexercise',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='instructions',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='media',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(related_name='exercises', to='api.musclegroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
