# Generated by Django 5.1.1 on 2024-10-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_mealplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='name',
            field=models.CharField(default='Default Plan Name', max_length=100),
        ),
    ]
