# Generated by Django 5.1.1 on 2024-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_workoutexercise_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(default='No instructions available'),
        ),
    ]
