# Generated by Django 5.1.1 on 2024-10-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mealplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietpreferences',
            name='macronutrient_intake',
        ),
    ]
