# Generated by Django 5.1.1 on 2024-10-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dietcategory_remove_macrosrecommendation_diet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='days_per_week',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('ligero', 'Ligero'), ('moderado', 'Moderado'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='moderado', max_length=10),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='workout',
            name='equipment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workout',
            name='training_preference',
            field=models.CharField(default='gimnasio', max_length=50),
        ),
    ]
