# Generated by Django 5.1.1 on 2024-10-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_dietpreferences_macronutrient_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='weight_goal',
            field=models.CharField(choices=[('gain_muscle', 'Ganar masa muscular'), ('lose_weight', 'Perder peso'), ('maintain', 'Mantenimiento')], max_length=20),
        ),
    ]
