# Generated by Django 5.1.1 on 2024-10-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workout_days_per_week_workout_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='days_per_week',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='training_preference',
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media', models.URLField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('ligero', 'Ligero'), ('moderado', 'Moderado'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('equipment', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('workouts', models.ManyToManyField(related_name='training_plans', to='api.workout')),
            ],
        ),
    ]
