# Generated by Django 5.1.1 on 2024-10-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userdetails_physical_activity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='physical_activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentaria'), ('light', 'Ligera'), ('moderate', 'Moderada'), ('intense', 'Intensa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usernutritionplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_nutrition_plans', to='api.user'),
        ),
    ]
