# Generated by Django 5.1.1 on 2024-10-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_workout_days_per_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='current_training_days',
        ),
    ]
