# Generated by Django 5.1.1 on 2024-10-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userdetails_current_training_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingpreferences',
            name='training_preference',
        ),
        migrations.AlterField(
            model_name='trainingpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='available_equipment', to='api.user'),
        ),
    ]
