# Generated by Django 5.1.1 on 2024-10-27 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userdetails_physical_activity_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('user_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_workouts', to='api.userworkout')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workout')),
            ],
        ),
    ]
