# Generated by Django 5.1.1 on 2024-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_weeklyworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyworkout',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
