# Generated by Django 5.1.1 on 2024-10-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_trainingpreferences_training_preference_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalConditions',
        ),
    ]
