# Generated by Django 5.1.1 on 2024-10-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_weightrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='available_equipment',
            field=models.CharField(choices=[('gimnasio_completo', 'Gimnasio Completo'), ('pesas_libres', 'Pesas Libres'), ('sin_equipamiento', 'Sin Equipamiento')], default='sin_equipamiento', max_length=20),
        ),
    ]
