# Generated by Django 5.1.1 on 2024-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userdetails_available_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_assignment', 'Awaiting Assignment'), ('assigned', 'Assigned'), ('active', 'Active')], default='awaiting_assignment', max_length=20),
        ),
    ]
