# Generated by Django 5.1.1 on 2024-10-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal_distribution',
            field=models.JSONField(blank=True, default=dict, help_text="Distribución de comidas en porcentajes. Ejemplo: {'desayuno': 20, 'almuerzo': 40, 'cena': 25, 'merienda': 15}", null=True),
        ),
        migrations.AlterField(
            model_name='dietpreferences',
            name='diet_type',
            field=models.CharField(choices=[('low_protein', 'Bajo en proteínas'), ('low_carbs', 'Bajo en carbohidratos'), ('low_fats', 'Bajo en grasas'), ('balanced', 'Balanceado')], default='balanced', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('awaiting_assignment', 'Awaiting Assignment'), ('assigned', 'Assigned'), ('training_only', 'Training Plan Assigned Only'), ('nutrition_only', 'Nutrition Plan Assigned Only')], default='awaiting_assignment', max_length=20),
        ),
    ]
