# Generated by Django 5.1.1 on 2024-11-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_mealplan_description_mealplan_meal_distribution_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietCategory',
        ),
    ]
