# Generated by Django 5.1.1 on 2024-11-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_dietcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='rest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
