# Generated by Django 5.1.1 on 2024-11-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_userworkout_training_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
    ]
