# Generated by Django 5.1.1 on 2024-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_trainingplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
