# Generated by Django 5.1.3 on 2024-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_mealplan_carbs_alter_mealplan_fats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='physical_activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('intense', 'Intense')], max_length=20),
        ),
    ]
