# Generated by Django 5.1.3 on 2024-11-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
