# Generated by Django 5.1.3 on 2024-12-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_user_role_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
