# Generated by Django 5.1.3 on 2024-12-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='media',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
