# Generated by Django 5.1.3 on 2024-12-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_workout_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='media',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='media',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
