# Generated by Django 5.1.3 on 2024-12-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_exercise_media_alter_trainingplan_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='media',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='media',
        ),
    ]
